import { LegalPage } from '@/components/public/LegalPage';

export default function Privacy() {
    return (
        <LegalPage
            title="Privacy Policy"
            updatedAt="August 1, 2026"
            sections={[
                {
                    heading: '1. Information We Collect',
                    body: [
                        'We collect information you provide directly, such as your name, email address, mobile number, and payment or withdrawal account details, along with information generated by your use of the platform, such as transaction history and login activity.',
                    ],
                },
                {
                    heading: '2. How We Use Your Information',
                    body: [
                        'We use your information to operate your account, process deposits and withdrawals, calculate earning cycles and referral bonuses, communicate service updates, and meet our legal and compliance obligations.',
                    ],
                },
                {
                    heading: '3. Sharing of Information',
                    body: [
                        'We do not sell your personal information. We may share limited data with payment processors to complete deposits and withdrawals, and with regulators or law enforcement where required by law.',
                    ],
                },
                {
                    heading: '4. Data Retention',
                    body: [
                        'We retain account and transaction records for as long as your account is active and for a further period afterward as required to meet legal, accounting, or reporting obligations.',
                    ],
                },
                {
                    heading: '5. Security',
                    body: [
                        'We apply reasonable technical and organizational safeguards to protect your information. No method of transmission or storage is completely secure, and we encourage you to use a strong, unique password.',
                    ],
                },
                {
                    heading: '6. Your Choices',
                    body: [
                        'You may review and update your profile information from your account settings at any time. To request deletion of your account, contact support — some records may be retained where required by law.',
                    ],
                },
                {
                    heading: '7. Contact',
                    body: ['Questions about this policy can be sent to support@silverquantx.com.'],
                },
            ]}
        />
    );
}
