name: Laravel React FTP Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: 🚀 Deploy to aaPanel
    runs-on: ubuntu-latest

    steps:

      # 1. Get latest source code
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      # 2. Upload source code to aaPanel
      - name: 📂 Upload source to aaPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 84.247.187.184
          username: ftp_abid_movievideos_site
          password: 2bf3392c2f2f
            protocol: ftp
          timeout: 9999999

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            .env
            .env.*
            tests/**
            storage/logs/**
            public/build/**